Repository Intro-to-SE-Spring-21/Group-8, pull requests merged in 2021-02, with the labels that each got.

#63 Populate update61
  Account/management/commands/populateDatabase.py
  Main_Page/templates/Main_Page/index.html
Labels: bug

#66 ViewPost_Issue#55
  Account/templates/Account/profile.html
  Account/templatetags/__init__.py
  Account/templatetags/nbsp.py
  Account/views.py
Labels: enhancement

#79 'Who to follow' checks to see if already followed + working follow bu…
  Account/templates/Account/profile.html
  Account/views.py
  Main_Page/templates/Main_Page/index.html
  Main_Page/views.py
Labels: Core Feature, enhancement

#80 Update read me #62
  README.md
Labels: documentation
